ALTER TABLE public.churches
ADD COLUMN IF NOT EXISTS pastor_name TEXT,
ADD COLUMN IF NOT EXISTS district TEXT;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS whatsapp TEXT,
ADD COLUMN IF NOT EXISTS cancellation_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS state TEXT;
